export const USUARIO_AUTENTICADO='USUARIO_AUTENTICADO';
export const REGISTRO_EXITOSO='REGISTRO_EXITOSO';
export const REGISTRO_ERROR='REGISTRO_ERROR';

export const LOGIN_ERROR='LOGIN_ERROR';
export const LOGIN_CORRECTO='LOGIN_CORRECTO';

export const OCULTAR_ALERTA='OCULTAR_ALERTA';
export const CERRAR_SESION='CERRAR_SESION';